export function installCurveHandleMethods(BirdWeightEditor, deps) {
  const {
    THREE,
    CURVE_CHANNELS,
    finitePoseValue
  } = deps;

  Object.assign(BirdWeightEditor.prototype, {
    shouldUseLinearCurveInterpolation() {
      return this.poseKeyframeMode === "replace"
        && this.poseKeyframes.size > 0
        && this.timelineKeysSourceWasAutoGenerated;
    },

    curveHandleKey(boneName, channel) {
      return `${boneName || ""}\u0000${channel || ""}`;
    },

    curveHandleMapFor(boneName, channel, { create = false } = {}) {
      if (!this.poseCurveHandles) {
        this.poseCurveHandles = new Map();
      }
      const key = this.curveHandleKey(boneName, channel);
      let handles = this.poseCurveHandles.get(key);
      if (!handles && create) {
        handles = new Map();
        this.poseCurveHandles.set(key, handles);
      }
      return handles || null;
    },

    curveHandleFor(boneName, channel, frame) {
      const handles = this.curveHandleMapFor(boneName, channel);
      return handles?.get(Math.round(frame)) || null;
    },

    setCurveHandleFor(boneName, channel, frame, handle = {}) {
      if (!boneName || !CURVE_CHANNELS[channel]) {
        return;
      }
      const normalized = {};
      if (Number.isFinite(Number(handle.inSlope))) {
        normalized.inSlope = finitePoseValue(handle.inSlope);
      }
      if (Number.isFinite(Number(handle.outSlope))) {
        normalized.outSlope = finitePoseValue(handle.outSlope);
      }
      const targetFrame = Math.max(0, Math.min(this.timelineFrames, Math.round(frame)));
      const handles = this.curveHandleMapFor(boneName, channel, { create: true });
      if (Object.keys(normalized).length) {
        handles.set(targetFrame, normalized);
      } else {
        handles.delete(targetFrame);
      }
      if (!handles.size) {
        this.poseCurveHandles.delete(this.curveHandleKey(boneName, channel));
      }
    },

    deleteCurveHandleFor(boneName, channel, frame, side = "") {
      const handles = this.curveHandleMapFor(boneName, channel);
      const targetFrame = Math.round(frame);
      const handle = handles?.get(targetFrame);
      if (!handle) {
        return;
      }
      if (side === "in") {
        delete handle.inSlope;
      } else if (side === "out") {
        delete handle.outSlope;
      } else {
        handles.delete(targetFrame);
        return;
      }
      if (!Object.keys(handle).length) {
        handles.delete(targetFrame);
      }
      if (!handles.size) {
        this.poseCurveHandles.delete(this.curveHandleKey(boneName, channel));
      }
    },

    deleteCurveHandlesForChannel(boneName, channel) {
      this.poseCurveHandles?.delete(this.curveHandleKey(boneName, channel));
    },

    deleteCurveHandlesForPoint(boneName, channel, frame) {
      this.deleteCurveHandleFor(boneName, channel, frame);
    },

    interpolateCurveChannel(keyed, frame, options = {}) {
      if (!keyed.length) {
        return 0;
      }
      if (keyed.length === 1) {
        return keyed[0].value;
      }
      const sorted = [...keyed].sort((a, b) => a.frame - b.frame);
      const exact = sorted.find((item) => item.frame === frame);
      if (exact) {
        return exact.value;
      }

      const nextIndex = sorted.findIndex((item) => item.frame >= frame);
      if (nextIndex <= 0) {
        return sorted[0].value;
      }
      if (nextIndex === -1) {
        return sorted[sorted.length - 1].value;
      }

      const p1Index = nextIndex - 1;
      const p2Index = nextIndex;
      const p1 = sorted[p1Index];
      const p2 = sorted[p2Index];
      const looped = sorted[0].frame === 0
        && sorted[sorted.length - 1].frame === this.timelineFrames
        && Math.abs(sorted[0].value - sorted[sorted.length - 1].value) < 0.0001;
      const span = Math.max(p2.frame - p1.frame, 1);
      const t = THREE.MathUtils.clamp((frame - p1.frame) / span, 0, 1);
      const p1Handle = this.curveHandleFor(options.boneName, options.channel, p1.frame);
      const p2Handle = this.curveHandleFor(options.boneName, options.channel, p2.frame);
      const hasCurveHandles = Number.isFinite(Number(p1Handle?.outSlope)) || Number.isFinite(Number(p2Handle?.inSlope));
      if (this.shouldUseLinearCurveInterpolation(options) && !hasCurveHandles) {
        return p1.value + (p2.value - p1.value) * t;
      }

      const t2 = t * t;
      const t3 = t2 * t;
      const outSlope = Number.isFinite(Number(p1Handle?.outSlope))
        ? finitePoseValue(p1Handle.outSlope)
        : this.curveAutoSmoothSlope(sorted, p1Index, looped);
      const inSlope = Number.isFinite(Number(p2Handle?.inSlope))
        ? finitePoseValue(p2Handle.inSlope)
        : this.curveAutoSmoothSlope(sorted, p2Index, looped);
      const m1 = outSlope * span;
      const m2 = inSlope * span;
      const value = (2 * t3 - 3 * t2 + 1) * p1.value
        + (t3 - 2 * t2 + t) * m1
        + (-2 * t3 + 3 * t2) * p2.value
        + (t3 - t2) * m2;
      return THREE.MathUtils.clamp(value, Math.min(p1.value, p2.value), Math.max(p1.value, p2.value));
    },

    curveAutoSmoothSlope(points, index, looped = false) {
      const current = points[index];
      if (!current) {
        return 0;
      }
      const previous = this.curveNeighborPoint(points, index, -1, looped);
      const next = this.curveNeighborPoint(points, index, 1, looped);
      if (!previous && !next) {
        return 0;
      }
      if (!previous) {
        return this.curveLinearSlope(current, next);
      }
      if (!next) {
        return this.curveLinearSlope(previous, current);
      }

      const incoming = this.curveLinearSlope(previous, current);
      const outgoing = this.curveLinearSlope(current, next);
      if (
        !Number.isFinite(incoming)
        || !Number.isFinite(outgoing)
        || Math.abs(incoming) < 0.000001
        || Math.abs(outgoing) < 0.000001
        || Math.sign(incoming) !== Math.sign(outgoing)
      ) {
        return 0;
      }
      const incomingFrames = Math.max(current.frame - previous.frame, 1);
      const outgoingFrames = Math.max(next.frame - current.frame, 1);
      const incomingWeight = 2 * outgoingFrames + incomingFrames;
      const outgoingWeight = outgoingFrames + 2 * incomingFrames;
      return (incomingWeight + outgoingWeight)
        / (incomingWeight / incoming + outgoingWeight / outgoing);
    },

    curveNeighborPoint(points, index, direction, looped = false) {
      if (direction < 0) {
        if (index > 0) {
          return points[index - 1];
        }
        if (looped && points.length > 2) {
          const wrapped = points[points.length - 2];
          return { frame: wrapped.frame - this.timelineFrames, value: wrapped.value };
        }
        return null;
      }
      if (index < points.length - 1) {
        return points[index + 1];
      }
      if (looped && points.length > 2) {
        const wrapped = points[1];
        return { frame: this.timelineFrames + wrapped.frame, value: wrapped.value };
      }
      return null;
    },

    curveLinearSlope(previous, next) {
      const frameSpan = Math.max(next.frame - previous.frame, 1);
      return (next.value - previous.value) / frameSpan;
    },

    serializePoseCurveHandles() {
      if (!this.poseCurveHandles?.size) {
        return [];
      }
      const result = [];
      for (const [key, handles] of this.poseCurveHandles.entries()) {
        const [boneName, channel] = String(key).split("\u0000");
        if (!boneName || !CURVE_CHANNELS[channel] || !handles?.size) {
          continue;
        }
        const keyed = [...handles.entries()]
          .filter(([keyedFrame]) => this.poseKeyframes.get(keyedFrame)?.[boneName]?.[channel] !== undefined)
          .sort(([a], [b]) => a - b)
          .map(([keyedFrame, handle]) => ({
            frame: keyedFrame,
            ...(Number.isFinite(Number(handle?.inSlope)) ? { inSlope: finitePoseValue(handle.inSlope) } : {}),
            ...(Number.isFinite(Number(handle?.outSlope)) ? { outSlope: finitePoseValue(handle.outSlope) } : {})
          }))
          .filter((handle) => handle.inSlope !== undefined || handle.outSlope !== undefined);
        if (keyed.length) {
          result.push({ bone: boneName, channel, keys: keyed });
        }
      }
      result.sort((a, b) => `${a.bone}.${a.channel}`.localeCompare(`${b.bone}.${b.channel}`));
      return result;
    },

    applySerializedPoseCurveHandles(serialized = []) {
      this.poseCurveHandles = new Map();
      if (!Array.isArray(serialized)) {
        return;
      }
      for (const curve of serialized) {
        const boneName = String(curve?.bone || curve?.boneName || "");
        const channel = String(curve?.channel || "");
        if (!boneName || !CURVE_CHANNELS[channel] || !Array.isArray(curve?.keys)) {
          continue;
        }
        for (const key of curve.keys) {
          if (!Number.isInteger(key?.frame)) {
            continue;
          }
          this.setCurveHandleFor(boneName, channel, key.frame, key);
        }
      }
    },

    curveHandleSpanForKey(keys, index, side) {
      const key = keys[index];
      if (!key) {
        return 0;
      }
      const neighbor = side === "in" ? keys[index - 1] : keys[index + 1];
      if (!neighbor) {
        return 0;
      }
      const frameSpan = Math.max(1, Math.abs(neighbor.frame - key.frame));
      return Math.max(3, Math.min(12, frameSpan / 2));
    },

    curveHandleControlPoints(boneName = this.curveBoneName?.(), channel = this.curveChannel?.()) {
      const keys = this.curveKeyFramesFor?.(boneName, channel) || [];
      if (keys.length < 2) {
        return [];
      }
      const points = [];
      for (let index = 0; index < keys.length; index += 1) {
        const key = keys[index];
        const handle = this.curveHandleFor(boneName, channel, key.frame);
        if (!handle) {
          continue;
        }
        for (const side of ["in", "out"]) {
          const slope = side === "in" ? handle.inSlope : handle.outSlope;
          if (!Number.isFinite(Number(slope))) {
            continue;
          }
          const span = this.curveHandleSpanForKey(keys, index, side);
          if (!span) {
            continue;
          }
          const direction = side === "in" ? -1 : 1;
          points.push({
            side,
            frame: key.frame,
            value: key.value,
            handleFrame: key.frame + direction * span,
            handleValue: key.value + direction * finitePoseValue(slope) * span,
            span,
            slope: finitePoseValue(slope)
          });
        }
      }
      return points;
    },

    drawCurveHandles(ctx, plot, config, boneName, channel) {
      const handles = this.curveHandleControlPoints(boneName, channel);
      if (!handles.length) {
        return;
      }
      ctx.save();
      ctx.lineWidth = 2;
      ctx.strokeStyle = "rgba(255, 207, 91, 0.9)";
      ctx.fillStyle = "rgba(255, 207, 91, 1)";
      for (const handle of handles) {
        const keyX = this.curveXForFrame(handle.frame, plot);
        const keyY = this.curveYForValue(handle.value, plot, config);
        const handleX = this.curveXForFrame(handle.handleFrame, plot);
        const handleY = this.curveYForValue(handle.handleValue, plot, config);
        ctx.strokeStyle = "rgba(26, 22, 16, 0.72)";
        ctx.lineWidth = 4;
        ctx.beginPath();
        ctx.moveTo(keyX, keyY);
        ctx.lineTo(handleX, handleY);
        ctx.stroke();
        ctx.strokeStyle = "rgba(255, 207, 91, 0.92)";
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(keyX, keyY);
        ctx.lineTo(handleX, handleY);
        ctx.stroke();
        ctx.beginPath();
        ctx.arc(handleX, handleY, 5, 0, Math.PI * 2);
        ctx.fillStyle = "rgba(26, 22, 16, 0.86)";
        ctx.fill();
        ctx.beginPath();
        ctx.arc(handleX, handleY, 3.25, 0, Math.PI * 2);
        ctx.fillStyle = "rgba(255, 207, 91, 1)";
        ctx.fill();
      }
      ctx.restore();
    },

    nearestCurveHandleFromPointer(event, threshold = 10) {
      if (!this.curveCanvas) {
        return null;
      }
      const rect = this.curveCanvas.getBoundingClientRect();
      const plot = this.curvePlotForRect(rect);
      const config = this.curveConfig();
      const pointerX = event.clientX - rect.left;
      const pointerY = event.clientY - rect.top;
      const boneName = this.curveBoneName();
      const channel = this.curveChannel();
      let nearest = null;
      for (const handle of this.curveHandleControlPoints(boneName, channel)) {
        const x = this.curveXForFrame(handle.handleFrame, plot);
        const y = this.curveYForValue(handle.handleValue, plot, config);
        const distance = Math.hypot(pointerX - x, pointerY - y);
        if (!nearest || distance < nearest.distance) {
          nearest = { ...handle, boneName, channel, distance };
        }
      }
      return nearest && nearest.distance <= threshold ? nearest : null;
    },

    setCurveHandleFromPointer(drag, event) {
      if (!drag || !this.curveCanvas) {
        return;
      }
      const rect = this.curveCanvas.getBoundingClientRect();
      const plot = this.curvePlotForRect(rect);
      const config = this.curveConfig();
      const y = THREE.MathUtils.clamp(event.clientY - rect.top, plot.top, rect.height - plot.bottom);
      const valueT = 1 - (y - plot.top) / plot.height;
      const handleValue = THREE.MathUtils.lerp(config.min, config.max, valueT);
      const direction = drag.side === "in" ? -1 : 1;
      const slope = direction * (handleValue - drag.value) / Math.max(0.0001, Math.abs(drag.handleFrame - drag.frame));
      const existing = this.curveHandleFor(drag.boneName, drag.channel, drag.frame) || {};
      this.markPoseKeyframesAuthored?.();
      this.setCurveHandleFor(drag.boneName, drag.channel, drag.frame, {
        ...existing,
        [drag.side === "in" ? "inSlope" : "outSlope"]: slope
      });
      this.applyPose(this.progress);
      this.syncPoseControlsToCurrentBone();
      this.syncPatchJson();
      this.drawCurveEditor();
    },

    clearCurveHandlesAroundPoint(boneName, channel, frame, sourceFrame = null) {
      this.deleteCurveHandlesForPoint(boneName, channel, frame);
      if (sourceFrame !== null && sourceFrame !== frame) {
        this.deleteCurveHandlesForPoint(boneName, channel, sourceFrame);
      }
    }
  });
}
